### ISSUE TITLE
Uncaught TypeError with fresh project

### ISSUE THREAD

**Issue by opdavies** [symfony/skeleton#52] opened 2018-01-08 21:12 UTC
Running the `composer create-project symfony/skeleton` command I immediately get an Uncaught TypeError fatal error.

Here is the full output:

```
➜  /tmp composer create-project symfony/skeleton test
Installing symfony/skeleton (v4.0.5)
  - Installing symfony/skeleton (v4.0.5): Loading from cache
Created project in test
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 21 installs, 0 updates, 0 removals
  - Installing symfony/flex (v1.0.58): Loading from cache
PHP Fatal error:  Uncaught TypeError: Argument 2 passed to Symfony\Flex\Response::__construct() must be of the type array, null given, called in /private/tmp/test/vendor/symfony/flex/src/Downloader.php on line 250 and defined in /private/tmp/test/vendor/symfony/flex/src/Response.php:27
Stack trace:
#0 /private/tmp/test/vendor/symfony/flex/src/Downloader.php(250): Symfony\Flex\Response->__construct(Array, NULL)
#1 /private/tmp/test/vendor/symfony/flex/src/Downloader.php(188): Symfony\Flex\Downloader->parseJson('{"ulid":"01C3BS...', 'https://symfony...', 'ulid')
#2 /private/tmp/test/vendor/symfony/flex/src/Downloader.php(170): Symfony\Flex\Downloader->fetchFile('https://symfony...', 'ulid', Array)
#3 /private/tmp/test/vendor/symfony/flex/src/Flex.php(382): Symfony\Flex\Downloader->get('/ulid')
#4 /private/tmp/test/vendor/symfony/flex/src/Flex.php(81): Symfony\Flex\Flex->getFlexId()
#5 phar:///usr/local/Cellar/composer/1.2.1/libexec/composer.phar/src/Composer/Plugin/PluginManager.php(236): Symfony\Flex\Flex->activate(Object(Compo in /private/tmp/test/vendor/symfony/flex/src/Response.php on line 27

Fatal error: Uncaught TypeError: Argument 2 passed to Symfony\Flex\Response::__construct() must be of the type array, null given, called in /private/tmp/test/vendor/symfony/flex/src/Downloader.php on line 250 and defined in /private/tmp/test/vendor/symfony/flex/src/Response.php:27
Stack trace:
#0 /private/tmp/test/vendor/symfony/flex/src/Downloader.php(250): Symfony\Flex\Response->__construct(Array, NULL)
#1 /private/tmp/test/vendor/symfony/flex/src/Downloader.php(188): Symfony\Flex\Downloader->parseJson('{"ulid":"01C3BS...', 'https://symfony...', 'ulid')
#2 /private/tmp/test/vendor/symfony/flex/src/Downloader.php(170): Symfony\Flex\Downloader->fetchFile('https://symfony...', 'ulid', Array)
#3 /private/tmp/test/vendor/symfony/flex/src/Flex.php(382): Symfony\Flex\Downloader->get('/ulid')
#4 /private/tmp/test/vendor/symfony/flex/src/Flex.php(81): Symfony\Flex\Flex->getFlexId()
#5 phar:///usr/local/Cellar/composer/1.2.1/libexec/composer.phar/src/Composer/Plugin/PluginManager.php(236): Symfony\Flex\Flex->activate(Object(Compo in /private/tmp/test/vendor/symfony/flex/src/Response.php on line 27
```

I've run `composer self-update` to ensure that I'm using the latest version of Composer, `1.6.2 2018-01-05 15:28:41`, and also run `composer clear-cache` to ensure that I'm getting the latest versions.

**Comment by nicolas-grekas** [comment] 2018-01-08 22:32
duplicate of https://github.com/symfony/flex/issues/277, fixed by https://github.com/symfony/flex/pull/279.

**Closed by nicolas-grekas** 2018-01-08 22:32 UTC
