### ISSUE TITLE
Duplicate in composer.json

### ISSUE THREAD

**Issue by Marenzio87** [symfony/skeleton#186] opened 2020-07-17 13:05 UTC
From launching "composer validate" on fresh installation: 

> symfony/monolog-bundle, symfony/twig-bundle are required both in require and require-dev, this can lead to unexpected behavior

**Comment by renanbr** [comment] 2020-07-17 13:17
I got the same problem when using `--unpack`, see https://github.com/symfony/flex/issues/597

and maybe related: https://github.com/symfony/flex/issues/654

**Comment by fabpot** [comment] 2020-08-29 06:44
Closing as a duplicate of https://github.com/symfony/flex/issues/654

**Closed as completed by fabpot** 2020-08-29 06:44 UTC
